import { ITextFieldOptions } from '../fields/textfields';
import { INumberFieldOptions } from '../fields/numberfields';
import { IFieldOptions } from '../fields/field';
import { ISelectionFieldOptions } from '../fields/selectionfields';
export declare function TextField(label: string, options?: ITextFieldOptions): (target: any, propName: string) => void;
export declare function PasswordField(label: string, options?: ITextFieldOptions): (target: any, propName: string) => void;
export declare function EmailField(label: string, options?: ITextFieldOptions): (target: any, propName: string) => void;
export declare function URLField(label: string, options?: ITextFieldOptions): (target: any, propName: string) => void;
export declare function NumberField(label: string, options?: INumberFieldOptions): (target: any, propName: string) => void;
export declare function IntegerField(label: string, options?: INumberFieldOptions): (target: any, propName: string) => void;
export declare function BooleanField(label: string, options?: IFieldOptions): (target: any, propName: string) => void;
export declare function SelectionField(label: string, selection: string[][], options?: ISelectionFieldOptions): (target: any, propName: string) => void;
export declare function DateField(label: string, options?: IFieldOptions): (target: any, propName: string) => void;
export declare function TimeField(label: string, options?: IFieldOptions): (target: any, propName: string) => void;
export declare function DateTimeField(label: string, options?: IFieldOptions): (target: any, propName: string) => void;
